#!/usr/bin/env python

import argparse
from pathlib import Path

import pandas as pd


def _extract_nvtx(name: str) -> str | None:
    if "<default domain>:" not in name:
        return None
    nvtx = name.split("<default domain>:", 1)[1]
    nvtx = nvtx.strip().strip('"')
    if ":" in nvtx:
        nvtx = nvtx.split(":", 1)[0]
    return nvtx


def _group_prefix(nvtx: str, depth: int) -> str:
    parts = nvtx.split(".")
    return ".".join(parts[:depth]) if depth > 0 else nvtx


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze NCU *_bounds.csv for memory-bound hotspots.")
    parser.add_argument("--csv", required=True, help="Path to *_bounds.csv from plot_ncu_roofline.py.")
    parser.add_argument("--top-k", type=int, default=20, help="Number of kernels to show.")
    parser.add_argument(
        "--min-mem-bw",
        type=float,
        default=50.0,
        help="Minimum mem_bw_pct to consider memory-bound (percent).",
    )
    parser.add_argument(
        "--max-vert-dist",
        type=float,
        default=1e12,
        help="Maximum vertical_distance to consider memory-bound (smaller is closer to roof).",
    )
    parser.add_argument(
        "--group-depth",
        type=int,
        default=5,
        help="NVTX path depth for aggregation (e.g., 5 -> policy.model.paligemma_with_expert...).",
    )
    parser.add_argument(
        "--plot",
        action="store_true",
        help="Write a simple PNG plot for aggregated groups.",
    )
    parser.add_argument(
        "--out-prefix",
        default=None,
        help="Output prefix for analysis files (default: <csv_stem>_analysis).",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    name_col = df.columns[0]
    required_cols = {"bound", "vertical_distance", "mem_bw_pct", "duration_s"}
    missing = required_cols - set(df.columns)
    if missing:
        missing_list = ", ".join(sorted(missing))
        raise SystemExit(
            f"Missing columns: {missing_list}. "
            "Use the *_bounds.csv generated by plot_ncu_roofline.py --out-list."
        )

    df["nvtx"] = df[name_col].astype(str).map(_extract_nvtx)
    df["has_nvtx"] = df["nvtx"].notna()
    df["mem_bound_strict"] = (
        (df["bound"].astype(str).str.lower() == "memory")
        & (df["mem_bw_pct"] >= args.min_mem_bw)
        & (df["vertical_distance"] <= args.max_vert_dist)
    )
    df["mem_bound"] = df["bound"].astype(str).str.lower() == "memory"
    df["comp_bound"] = df["bound"].astype(str).str.lower() == "compute"

    eps = 1e-9
    df["mem_score"] = (df["mem_bw_pct"] * df["duration_s"]) / (df["vertical_distance"].abs() + eps)

    mem_df = df[df["mem_bound_strict"]].copy()
    mem_df = mem_df.sort_values(by=["mem_score", "mem_bw_pct"], ascending=[False, False])

    print("Top memory-bound kernels (leaf-level rows):")
    cols = [name_col, "bound", "vertical_distance", "mem_bw_pct", "duration_s"]
    print(mem_df[cols].head(args.top_k).to_string(index=False))

    nvtx_df = df[df["has_nvtx"]].copy()
    nvtx_df["group"] = nvtx_df["nvtx"].map(lambda n: _group_prefix(n, args.group_depth))
    agg = nvtx_df.groupby("group", as_index=False).agg(
        total=("bound", "count"),
        mem_bound=("mem_bound", "sum"),
        mem_bound_strict=("mem_bound_strict", "sum"),
        comp_bound=("comp_bound", "sum"),
        avg_bw=("mem_bw_pct", "mean"),
        max_bw=("mem_bw_pct", "max"),
        avg_duration=("duration_s", "mean"),
        max_duration=("duration_s", "max"),
        min_vert_dist=("vertical_distance", "min"),
        avg_vert_dist=("vertical_distance", "mean"),
        best_score=("mem_score", "max"),
        avg_score=("mem_score", "mean"),
    )
    agg = agg.sort_values(by=["mem_bound_strict", "avg_bw", "best_score"], ascending=[False, False, False])

    print("\nMemory-bound aggregation by NVTX group:")
    print(agg.head(args.top_k).to_string(index=False))

    no_nvtx = len(df) - int(df["has_nvtx"].sum())
    print(f"\nRows without NVTX names: {no_nvtx} (cannot map to modules)")

    csv_path = Path(args.csv)
    out_prefix = Path(args.out_prefix) if args.out_prefix else csv_path.with_suffix("").with_name(
        csv_path.stem + "_analysis"
    )
    agg_out = out_prefix.with_suffix(".txt")
    with agg_out.open("w") as f:
        f.write("Top memory-bound kernels (leaf-level rows):\n")
        f.write(mem_df[cols].head(args.top_k).to_string(index=False))
        f.write("\n\nMemory-bound aggregation by NVTX group:\n")
        f.write(agg.head(args.top_k).to_string(index=False))
        f.write(f"\n\nRows without NVTX names: {no_nvtx} (cannot map to modules)\n")
    print(f"\nWrote: {agg_out}")

    if args.plot:
        try:
            import matplotlib.pyplot as plt
        except Exception:
            print("matplotlib not available; skipping plot.")
            return

        plot_df = agg.head(args.top_k).copy()
        plot_df = plot_df.sort_values(by="avg_bw", ascending=True)
        fig, ax = plt.subplots(figsize=(8, max(4, 0.3 * len(plot_df))))
        ax.barh(plot_df["group"], plot_df["avg_bw"], color="#3b82f6")
        ax.set_xlabel("avg mem_bw_pct")
        ax.set_title("Avg memory bandwidth by NVTX group")
        plt.tight_layout()
        plot_out = out_prefix.with_suffix(".png")
        fig.savefig(plot_out, dpi=150)
        print(f"Wrote: {plot_out}")


if __name__ == "__main__":
    main()
